notifications:
    email: false
language: C  
script:
    - cd test
    - make all MODA_WORD_SIZE=1
    - make all MODA_WORD_SIZE=2   
    - make all MODA_WORD_SIZE=4
    - make all MODA_WORD_SIZE=8
    
    

